server:
  port: 9009
spring:
  application:
    name: tensquare_sms
  rabbitmq:
    host: 172.30.61.251
aliyun:
  sms:
    accessKeyId: LTAI4FpEQoictmHdpHSnkrxy
    accessKeySecret: vOMEMh6gBg87EP8Nh3VYt18UEzDPnr
    template_code: SMS_175583762
    sign_name: 运维007