server: 
  port: 9005
spring: 
  application:  
    name: tensquare-gathering #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.30.60.14:3306/tensquare_gathering?characterEncoding=UTF8&useSSL=false&allowMultiQueries=true
    username: stest1
    password: P@ssw0rd1
    dbcp2:
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 3600000
  jpa: 
    database: mysql
    show-sql: true
    properties:
      hibernate.format_sql: true
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace
